

services:

  postgres:
    image: postgres:17
    container_name: postgres_server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: my_database
    volumes:
      - pgsql_data:/var/lib/postgresql/data


  dbgate:
    image: dbgate/dbgate
    container_name: dbgate
    restart: always
    ports:
      - "3000:3000" # Access DBGate at http://localhost:8080
    volumes:
      # - dbgate-data:/root/.dbgate
      - dbgate-data_test:/root/.dbgate
    environment:
      CCONNECTIONS: con2



      LABEL_con2: PostgreSQL
      SERVER_con2: postgres
      USER_con2: postgres
      PASSWORD_con2: postgres
      PORT_con2: 5432
      ENGINE_con2: postgres@dbgate-plugin-postgres
      DATABASE_con2: my_database

    depends_on:
      - postgres


volumes:
  pgsql_data:
  dbgate-data:
  dbgate-data_test:
    driver: local
